name: MinigameCore
main: net.craftgalaxy.minigamecore.MinigameCore
version: 1.0.0
api-version: 1.16
author: Frank
commands:
  settings:
    description: Set the seed for the generated terrain
depend:
  - MinigameService
  - Manhunt
  - DeathSwap